name: My WorkFlow
on:
  push:
    # branches: ["main","develop"]
    branches: ["main"]
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: one line script
        run: echo hello github action
      - name: multi line script
        run: |
          echo hello github action
          echo this is CI/CD
  second-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: second-job-echo
        run: echo hello second job
